MWBTCustomerCreation/CCAPortal/Controllers/SMSTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WBT.DLCustomerCreation;

namespace CCAPortal.Controllers
{
    public class SMSTemplatesController : Controller
    {
        DLTemplates dLTemplates = new DLTemplates();
        // GET: SMSTemplates
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                return PartialView();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Templates templates)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                Templates Result = dLTemplates.SaveSMSTemplate(templates, Session["OrgID"].ToString(), Session["UserID"].ToString());
                return Json(Result.DisplayMessage);
            }
            else
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Json(new { allErrors });
            }
        }
        public ActionResult TemplateList()
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }

            List<Templates> result = new List<Templates>();
            try
            {
                result = dLTemplates.GetSMSTemplates(Session["OrgID"].ToString());
            }
            catch (Exception ex)
            {

            }
            return PartialView(result);
        }
        public ActionResult Edit(int ID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Templates templates = dLTemplates.GetSMSTemplateDetails(ID);

            if (templates == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", templates);
        }
        public ActionResult Delete(int ID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Templates Result = dLTemplates.DeleteSMSTemplate(ID, Session["OrgID"].ToString(), Session["UserID"].ToString());
            return Json(Result.DisplayMessage, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Templates templates)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ModelState.IsValid)
            {
                Templates Result = dLTemplates.SaveSMSTemplate(templates, Session["OrgID"].ToString(), Session["UserID"].ToString());
                return Json(new
                {
                    Message = Result.DisplayMessage,
                    AjaxReturn = PartialView("TemplateList", dLTemplates.GetSMSTemplates(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
            else
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Json(new
                {
                    Message = allErrors,
                    AjaxReturn = PartialView("TemplateList", dLTemplates.GetSMSTemplates(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
        }
    }
}

MWBTCustomerCreation/CCAPortal/Views/SMSTemplates/Create.cshtml
@model WBT.DLCustomerCreation.Templates
@using (Ajax.BeginForm("Save", "SMSTemplates", null, new AjaxOptions
{
    OnSuccess = "onCreateSuccess_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">SMS Templates</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Template Name </label>
                                @Html.EditorFor(model => model.TemplateName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Template Name", @autocomplete = "off", @required = "required" } })
                                @Html.ValidationMessageFor(model => model.TemplateName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Message</label>
                                @Html.TextAreaFor(model => model.TemplateBody, new { @class = "form-control", @placeholder = "Message", @autocomplete = "off", @required = "required" })
                                @Html.ValidationMessageFor(model => model.TemplateBody, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $.validator.unobtrusive.parse(document);
</script>

MWBTCustomerCreation/CCAPortal/Views/SMSTemplates/Edit.cshtml
@model WBT.DLCustomerCreation.Templates
@using (Ajax.BeginForm("Update", "SMSTemplates", null, new AjaxOptions
{
    OnSuccess = "onEditSuccess_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Edit SMS Template</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Template Name </label>
                                <div class="input-group">
                                    @Html.HiddenFor(model => model.ID)
                                    @Html.EditorFor(model => model.TemplateName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Template Name", @autocomplete = "off", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.TemplateName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Message</label>
                                <div class="input-group">
                                    <div class="input-group">
                                        @Html.TextAreaFor(model => model.TemplateBody, new { @class = "form-control", @placeholder = "Message", @autocomplete = "off", @required = "required" })
                                    </div>
                                    @Html.ValidationMessageFor(model => model.TemplateBody, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $.validator.unobtrusive.parse(document);
</script>

MWBTCustomerCreation/CCAPortal/Views/SMSTemplates/Index.cshtml
@{
    ViewBag.Title = "SMS Templates";
}

<div class="main-panel" id="MainDiv">
    <div class="row">
        <div class="col-12 grid-margin">
            <div id="divCreate">
                @Html.Action("Create")
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 grid-margin">
            <div id="divList">
                @Html.Action("TemplateList")
            </div>
        </div>
    </div>
</div>

<div id="progress" class="modal">
    <div class="center" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            Loading, please wait... <img src="~/images/loading.gif" height="100" width="100" />
        </p>
    </div>
</div>

@section scripts {

    <script>
        function onCreateSuccess_Ajax(data) {
             Swal.fire({
                    text: data,
                }).then((result) => {
                    $("#divCreate").load('@Url.Action("Create", "SMSTemplates")');
                    $("#divList").load('@Url.Action("TemplateList", "SMSTemplates")');
                    setTimeout(function () {
                        loadDataTableWithButtons();
                    }, 1000);
                });
        }
        function onEditSuccess_Ajax(data) {
            Swal.fire({
                text: data.Message,
                }).then((result) => {
                    $("#divCreate").load('@Url.Action("Create", "SMSTemplates")');
                    $("#divList").load('@Url.Action("TemplateList", "SMSTemplates")');
                    setTimeout(function () {
                        loadDataTableWithButtons();
                    }, 1000);
                });
        }
        function onBegin_Ajax(data) {
        }
        function onErrorCreate(error) {

        }
        function Ajax_Edit_Failure(xhr, statusDescription) {
            swal(xhr.statusDescription);
        }
        function onEditSuccess() {
            $("#TemplateName").focus();
        }
        function onDeleteSuccess(data) {
            if (data.url) {
                window.location = '@Url.Action("Index", "Login")';
            }
            Swal.fire({
                text: data,
            }).then((result) => {
                $("#divCreate").load('@Url.Action("Create", "SMSTemplates")');
                $("#divList").load('@Url.Action("TemplateList", "SMSTemplates")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
        }
        function onEditCompleteCreate_Ajax() {

        }
        function Ajax_OnComplete() {

        }
        function onSaveCompleteCreate_Ajax() {

        }
    </script>
    <script>
        function btnCancel_Click() {
            $('#divCreate').load('@Url.Action("Create", "SMSTemplates")');
            setTimeout(function () {
                LoadListBox();
            }, 1000);
        }
    </script>

    <script>
        jQuery(document).ready(function ($) {
            loadDataTableWithButtons();
        });
    </script>

}

MWBTCustomerCreation/CCAPortal/Views/SMSTemplates/TemplateList.cshtml
@model IEnumerable<WBT.DLCustomerCreation.Templates>
<div class="row">
    <div class="col-12">
        <div>
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title"> SMS Templates List </h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <div>
                        <table class="table table-bordered table-striped" id="dataGrid">
                            <thead>
                                <tr>
                                    <th>
                                        Template Name
                                    </th>
                                    <th>
                                        Created Date
                                    </th>
                                    <th>
                                        Status
                                    </th>
                                    <th class="notexport">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.Count() > 0)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.HiddenFor(Model => item.ID)
                                                    @item.TemplateName
                                                </td>
                                                <td>
                                                    @item.CreatedDate.Value.ToString("dd/MM/yyyy")
                                                </td>
                                                <td>
                                                    @item.Status
                                                </td>
                                                <td>
                                                    @Ajax.ActionLink("Edit", "Edit", "SMSTemplates", new { ID = item.ID }, new AjaxOptions { UpdateTargetId = "divCreate", HttpMethod = "get", OnSuccess = "onEditSuccess", LoadingElementId = "progress" }, new { @class = "btn btn-info btn-xs" }) |
                                                    @Ajax.ActionLink("Delete", "Delete", "SMSTemplates", new { ID = item.ID }, new AjaxOptions { Confirm = "Are you sure you want to do this Template?", HttpMethod = "get", OnSuccess = "onDeleteSuccess", LoadingElementId = "progress" }, new { @class = "btn btn-danger btn-xs" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>