MWBTCustomerCreation/CCAPortal/Controllers/TaxLegdersMasterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using WBT.Common;
using WBT.DLCustomerCreation;
using WBT.DLCustomerCreation.DTOs;

namespace CCAPortal.Controllers
{
    public class TaxLegdersMasterController : Controller
    {
        // GET: TaxLegdersMaster
        DLTaxLedgers dLLedgerCreation = new DLTaxLedgers();
        CustomerCreations customerCreations = new CustomerCreations();
        public static string xmlFileString = string.Empty;
        static XmlDocument xmlDoc = new XmlDocument();
        static string mxmlRootPath = string.Empty;
        bool IsCompanyOpen = false;
        private static TimeZoneInfo INDIAN_ZONE = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");
        TallySync tallySync = new TallySync();
        // GET: Debtors
        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                ViewBag.TaxLedgerList = new SelectList(dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()), "ID", "Name");
                return View(dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public ActionResult Create()
        {
            ViewBag.TaxList = new SelectList(dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()), "OrgID", "Name");
            ViewBag.TaxTypeList = new SelectList(dLLedgerCreation.GetTaxTypesList(Session["OrgID"].ToString()), "TaxType", "TaxType");

            //CGST: Central Goods and Services Tax
            //SGST: State Goods and Services Tax
            //IGST: Integrated Goods and Services Tax

            return PartialView();
        }
        public ActionResult TaxLedgerList()
        {
            return PartialView(dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(TaxLedgersDTO taxLedgers)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                int ID = dLLedgerCreation.SaveTaxLedger(taxLedgers, Session["UserID"].ToString(), Session["OrgID"].ToString());
                if (ID > 0)
                {
                    ModelState.Clear();
                    return Json(new
                    {
                        ID = ID,
                        Message = "success",
                        AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                    });
                }
                else
                {
                    return Json(new
                    {
                        ID = 0,
                        Message = "TaxLedger Name already exists",
                        AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                    });
                }
            }
            else
            {
                return Json(new
                {
                    Status = 0,
                    Message = "error",
                    AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
        }
        public ActionResult Edit(int? ID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.TaxLedgerList = new SelectList(dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()), "ID", "Name");
            ViewBag.TaxTypeList = new SelectList(dLLedgerCreation.GetTaxTypesList(Session["OrgID"].ToString()), "TaxType", "TaxType");
            TaxLedgersDTO obj = dLLedgerCreation.GetTaxLedgerDetail(ID);

            if (obj == null)
            {
                return HttpNotFound();
            }

            return PartialView("Edit", obj);
        }
        public ActionResult Delete(int ID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DLRoleCreation Result = dLLedgerCreation.DeleteTaxLedger(ID, Session["OrgID"].ToString(), Session["UserID"].ToString());
            return Json(Result.DisplayMessage, JsonRequestBehavior.AllowGet);
        }       
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(TaxLedgersDTO Ledgers)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                int ID = dLLedgerCreation.SaveTaxLedger(Ledgers, Session["UserID"].ToString(), Session["OrgID"].ToString());
                if (ID > 0)
                {
                    ModelState.Clear();
                    return Json(new
                    {
                        ID = ID,
                        Message = "success",
                        AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                    });
                }
                else
                {
                    return Json(new
                    {
                        ID = 0,
                        Message = "TaxLedger Name already exists",
                        AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                    });
                }
            }
            else
            {
                return Json(new
                {
                    Status = 0,
                    Message = "error",
                    AjaxReturn = PartialView("TaxLedgerList", dLLedgerCreation.GetTaxLedgers(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
        }

        public bool IsTallyCompanyOpen(TaxLedgersDTO item, string BranchName, bool iswinservice = false)
        {
            //xmlFileString = System.IO.File.ReadAllText(@"DataFiles\IsCurrentCompanyOpen.xml");
            if (iswinservice == false)
            {
                xmlFileString = Server.MapPath("~/DataFiles/IsCurrentCompanyOpen.xml");
            }
            else
            {
                string xmlfile = Helper.GetSystemFilePath() + @"\DataFiles";
                Helper.LogError("IsCurrentCompanyOpen", xmlfile, null, "");
                xmlFileString = Path.Combine(xmlfile, "IsCurrentCompanyOpen.xml");
            }
            xmlDoc = new XmlDocument();
            xmlDoc.Load(xmlFileString);

            try
            {
                mxmlRootPath = "ENVELOPE/BODY/";
                xmlDoc.SelectSingleNode(mxmlRootPath + "/DESC/STATICVARIABLES/SVCOMPANYCONNECTNAME").InnerText = BranchName;
                string tempLedger = xmlDoc.InnerXml;
                string Result = XMLGetData(tempLedger);
                if (Result.Contains("<SERVERCOMPANYNAME>" + BranchName + "</SERVERCOMPANYNAME>"))
                {
                    IsCompanyOpen = true;
                    Helper.LogError("S7", "", null, "");
                }
                else if (Result.Contains("<DESC>Server company is not available!"))
                {
                    item.DisplayMsg = " Please Open Company " + BranchName + " In Tally";
                    IsCompanyOpen = false;
                }
                else
                {
                    item.DisplayMsg = Result;
                }
                return IsCompanyOpen;
            }
            catch (Exception ex)
            {
                Helper.LogError(ex.Message, ex.Source, null, ex.StackTrace);
                return false;
            }
        }
        public string XMLGetData(string XMLString)
        {
            string mXMLResult = string.Empty;
            try
            {
                XmlDocument XMLResponse = null;
                HttpWebResponse objHttpWebResponse = null;
                XmlTextReader objXMLReader = default(XmlTextReader);
                HttpWebRequest objHttpWebRequest = default(HttpWebRequest);
                objHttpWebRequest = (HttpWebRequest)WebRequest.Create(@"http://localhost:9000");
                byte[] bytes = null;
                bytes = System.Text.Encoding.ASCII.GetBytes(XMLString);
                objHttpWebRequest.Method = "POST";
                objHttpWebRequest.ContentLength = bytes.Length;
                objHttpWebRequest.ContentType = "text/xml; encoding='utf-8'";

                Stream objRequestStream = null;
                Stream objResponseStream = null;
                objRequestStream = objHttpWebRequest.GetRequestStream();
                objRequestStream.Write(bytes, 0, bytes.Length);


                objHttpWebRequest.KeepAlive = true;
                objHttpWebResponse = (HttpWebResponse)objHttpWebRequest.GetResponse();
                if (objHttpWebResponse.StatusCode == HttpStatusCode.OK)
                {
                    objResponseStream = objHttpWebResponse.GetResponseStream();

MWBTCustomerCreation/CCAPortal/Views/TaxLegdersMaster/Create.cshtml
@model WBT.DLCustomerCreation.DTOs.TaxLedgersDTO
@using (Ajax.BeginForm("Save", "TaxLegdersMaster", null, new AjaxOptions
{
    //UpdateTargetId = "divList",
    OnBegin = "onBegin_Ajax",
    OnComplete = "onSaveCompleteCreate_Ajax",
    OnSuccess = "onCreateSuccess_Ajax",
    OnFailure = "onFailure_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()

    <section>
        <div>
            <div>
                <!-- left column -->
                <div>
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Create Tax Ledgers</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label> Name </label>
                                        <div class="input-group">
                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name", @autocomplete = "off", @required = "Required" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                              <label>Tax Type </label>
                                    <div class="input-group">
                                    @Html.DropDownListFor(model => model.TaxType, (SelectList)ViewBag.TaxTypeList, "Select Tax Type", new { @class = "form-control listbox", @required = "required" })
                                    @Html.ValidationMessageFor(model => model.TaxType, "", new { @class = "text-danger" })
                                    </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Tax percentage</label>
                                        <div class="input-group">
                                            @Html.EditorFor(model => model.TaxPercentage, new { htmlAttributes = new { @class = "form-control numberonly", @placeholder = "Tax Percentage", @Value = "0.00", @required = "Required", @onkeypress = "return isdecimalKey(event)" } })
                                            @Html.ValidationMessageFor(model => model.TaxPercentage, "", new { @class = "text-danger" })                                          
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary" id="btnCreate">Create</button>
                                    <a href="javascript:void(0)" onclick="TallySync();" class="btn btn-success" id="btnTally" style="display:none;">Sync To Tally</a>
                                    <a href="javascript:void(0)" id="btnCancel" class="btn btn-danger" onclick="btnCancel_Click()">Cancel</a>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>

}
@section scripts{
    <script>
        function ddlParent_changed() {
            //var ddlParentID = $("#DebtorName option:selected").val();
            //$('#ParentDebtorID').val(ddlParentID);
        }
    </script>
    <script>
        $.validator.unobtrusive.parse(document);
    </script>
}

MWBTCustomerCreation/CCAPortal/Views/TaxLegdersMaster/Edit.cshtml
@model WBT.DLCustomerCreation.DTOs.TaxLedgersDTO

@using (Ajax.BeginForm("Update", "TaxLegdersMaster", null, new AjaxOptions
{
    //UpdateTargetId = "divList",
    OnBegin = "onBegin_Ajax",
    OnComplete = "onEditCompleteCreate_Ajax",
    OnSuccess = "onEditSuccess_Ajax",
    OnFailure = "onFailure_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()

    <div>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"> Update Tax Ledgers </h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div id="maindiv">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label> Name </label>
                                <div class="input-group">
                                    @Html.HiddenFor(model => model.ID)
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @required = "Required" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tax Type </label>
                                <div class="input-group">
                                    @Html.DropDownListFor(model => model.TaxType, (SelectList)ViewBag.TaxTypeList, "Select Tax Type", new { @class = "form-control listbox", @required = "required" })
                                </div>
                                @Html.ValidationMessageFor(model => model.TaxType, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tax Percentage </label>
                                <div class="input-group">   
                                    @Html.EditorFor(model => model.TaxPercentage, new { htmlAttributes = new { @class = "form-control ", @placeholder = "TaxPercentage", @required = "Required", @onkeypress = "return isdecimalKey(event)" } })
                                    @Html.ValidationMessageFor(model => model.TaxPercentage, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
   
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary" id="btnUpdate">Update Tax Ledgers</button>
                    <a href="javascript:void(0)" onclick="TallySync();" class="btn btn-success" id="btnTally">Sync To Tally</a>
                    <a href="javascript:void(0)" id="btnCancel" class="btn btn-danger" onclick="btnCancel_Click()">Cancel</a>
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
    <script>
        function ddlParent_changed() {
            //var ddlParentID = $("#DebtorName option:selected").val();
            //$('#ParentDebtorID').val(ddlParentID);
        }
    </script>
    <script>
        $.validator.unobtrusive.parse(document);
    </script>
}

MWBTCustomerCreation/CCAPortal/Views/TaxLegdersMaster/Index.cshtml
@model IEnumerable<WBT.DLCustomerCreation.DTOs.TaxLedgersDTO>
@{
    ViewBag.Title = "Tax Ledgers";
}

<div class="main-panel" id="MainDiv">
    <div class="row">
        @Html.Hidden("HID")
        <div class="col-12 grid-margin">
            <div id="divCreate">
                @*class="card-body"*@
                @Html.Action("Create")
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 grid-margin">
            <div id="divList">
                @*class="card-body"*@
                @Html.Action("TaxLedgerList")
            </div>
        </div>
    </div>
</div>

<div id="progress" class="modal">
    <div class="center" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;">
        <p style="position: absolute; color: White; top: 45%; left: 45%;">
            <span>Loading items, Please wait...</span> <img src="~/images/loading.gif" height="100" width="100" />
        </p>
    </div>
</div>

@section scripts {

    <script>
    function onCreateSuccess_Ajax(data) {
        if (data.Message == "success") {
            Swal.fire({
                title: 'Success!!',
                text: 'Tax Ledger Group Saved Successfully',
                icon: 'success',
            }).then((result) => {
                $("#HID").val(data.ID);
                $("#btnCreate").hide();
                $("#btnTally").show();
                $("#btnCancel").show();
                $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
            $("#HID").val(data.ID);
        }
        else {
            Swal.fire({
                title: 'Error',
                text: data.Message,
                icon: 'error',
            }).then((result) => {
                $("#HID").val(data.ID);
                $("#btnCreate").show();
                $("#btnTally").hide();
                $("#btnCancel").hide();
                $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
        }
    }
    function onEditSuccess_Ajax(data) {
        if (data.Message == "success") {
            Swal.fire({
                title: 'Success!!',
                text: 'Tax Ledger Updated Successfully',
                icon: 'success',
            }).then((result) => {
                $("#HID").val(data.ID);
                $("#btnUpdate").hide();
                $("#btnTally").show();
                $("#btnCancel").show();
                $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
            $("#HID").val(data.ID);
        }
        else {
            Swal.fire({
                title: 'Error',
                text: data.Message,
                icon: 'error',
            }).then((result) => {
                $('#divCreate').load('@Url.Action("Create", "TaxLegdersMaster")');
                $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
        }
        }
        function onDeleteSuccess(data) {
            if (data.url) {
                window.location = '@Url.Action("Index", "Login")';
            }
            Swal.fire({
                text: data,
            }).then((result) => {
                $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
        }
    function onBegin_Ajax(data) {
    }
    function onFailure_Ajax() {
        Swal.fire({
            title: 'Success!!',
            text: 'Please try again later',
            icon: 'success',
        }).then((result) => { });
    }
    function Ajax_Edit_Failure(xhr, statusDescription) {
        //swal(xhr.statusDescription);
        Swal.fire({
            title: 'Success!!',
            text: xhr.statusDescription,
            icon: 'success',
        }).then((result) => { });
    }
    function onEditSuccess() {
        $("#Name").focus();
        LoadListBox();
        document.getElementById("btnTally").style.display = "none";
        //document.getElementById("btnCancel").style.display = "none";
    }
    function onEditCompleteCreate_Ajax() {

    }
    function Ajax_OnComplete() {

    }
    function onSaveCompleteCreate_Ajax() {

    }
    $(document).ready(function () {
        document.getElementById("btnTally").style.display = "none";
        document.getElementById("btnCancel").style.display = "none";
    });
    </script>
    <script>
    function btnCancel_Click() {
        $('#divCreate').load('@Url.Action("Create", "TaxLegdersMaster")');
        setTimeout(function () {
            document.getElementById("btnTally").style.display = "none";
            document.getElementById("btnCancel").style.display = "none";
        }, 1000);
    }
    function LoadListBox() {
        $('.listbox').multiselect({
            includeSelectAllOption: true,
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            maxHeight: 450,
        });
    }
        function TallySync(ID) {
            var id = $("#ID").val();
        $.ajax({
            url: '@Url.Action("TallySync", "TaxLegdersMaster")',
            data: "{ 'ID': '" + id + "'}",
            dataType: "json",
            type: "POST",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data == "0") {
                    window.location = '@Url.Action("Index", "Login")';
                }
                else if (data == "1") {
                    swal.fire("Please install the service and open tally software, wait for 10 seconds and click on Tally Sync button again");
                }
                else {
                    if (data == "Tally Sync Successful!!") {
                        Swal.fire({
                            title: 'Success!!',
                            text: 'Tally Sync Successful!!',
                            icon: 'success',
                        }).then((result) => {
                            $('#divCreate').load('@Url.Action("Create", "TaxLegdersMaster")');
                            $("#divList").load('@Url.Action("TaxLedgerList", "TaxLegdersMaster")');
                            setTimeout(function () {
                                    $("#dataGrid").dataTable().fnDestroy();
                                    loadDataTableWithButtons();
                                }, 1000);
                            });
                        }
                    else {
                        swal.fire(data);
                    }
                }
            },
            error: function (response) {
                swal.fire(response.responseText);
            },
            failure: function (response) {
                swal.fire(response.responseText);
            }
        });
    }
    </script>
    <script>
        jQuery(document).ready(function ($) {
            loadDataTableWithButtons();
        });
    </script>
}