MWBTCustomerCreation/CCAPortal/Controllers/ItemCompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WBT.DLCustomerCreation;

namespace CCAPortal.Controllers
{
    public class ItemCompanyController : Controller
    {
        DLItemCompany DL = new DLItemCompany();
        // GET: ItemCompany
        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {

                return View(DL.GetData(Session["OrgID"].ToString()).ToList());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                return PartialView();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(ItemCompany itemCompany)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                ItemCompany Result = DL.SaveData(itemCompany, Session["OrgID"].ToString(), Session["UserID"].ToString());
                return Json(Result.DisplayMessage);
            }
            else
            {
                return Json("Error");
            }
        }
        public ActionResult CompanyList()
        {
            List<ItemCompany> result = new List<ItemCompany>();
            try
            {
                result = DL.GetData(Session["OrgID"].ToString());
            }
            catch (Exception ex)
            {

            }
            return PartialView(result);
        }
        public ActionResult Edit(int ItemCompanyID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ItemCompanyID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ItemCompany itemCompany = DL.GetItemCompanyDetail(ItemCompanyID);

            if (itemCompany == null)
            {
                return HttpNotFound();
            }
            return PartialView("Edit", itemCompany);
        }
        public ActionResult Delete(int ItemCompanyID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ItemCompanyID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DLRoleCreation Result = DL.DeleteItemCompany(ItemCompanyID, Session["OrgID"].ToString(), Session["UserID"].ToString());
            return Json(Result.DisplayMessage, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ItemCompany itemCompany)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json(new { url = Url.Action("Index", "Login") });
            }
            if (ModelState.IsValid)
            {
                ItemCompany Result = DL.SaveData(itemCompany, Session["OrgID"].ToString(), Session["UserID"].ToString());
                return Json(new
                {
                    Message = Result.DisplayMessage,
                    AjaxReturn = PartialView("CompanyList", DL.GetData(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
            else
            {
                return Json(new
                {
                    Message = "Error!!",
                    AjaxReturn = PartialView("CompanyList", DL.GetData(Session["OrgID"].ToString()).ToList()).RenderToString()
                });
            }
        }
    }
}

MWBTCustomerCreation/CCAPortal/Views/ItemCompany/CompanyList.cshtml
@model IEnumerable<WBT.DLCustomerCreation.ItemCompany>
<div class="row">
    <div class="col-12">
        <div>
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title"> Brand Manufacturers List </h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <div>
                        <table class="table table-bordered table-striped" id="dataGrid">
                            <thead>
                                <tr>
                                    <th>
                                        Brand Manufacturer Name
                                    </th>
                                    <th>
                                        Created Date
                                    </th>
                                    <th>
                                        Modified Date
                                    </th>
                                    <th>
                                        Status
                                    </th>
                                    <th class="notexport">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.Count() > 0)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.HiddenFor(Model => item.ItemCompanyID)
                                                    @item.CompanyName
                                                </td>
                                                <td>
                                                    @item.CreatedDate.Value.ToString("dd/MM/yyyy")
                                                </td>
                                                <td>
                                                    @{
                                                        if (@item.ModifiedDate != null)
                                                        {
                                                            @item.ModifiedDate.Value.ToString("dd/MM/yyyy");
                                                        }
                                                        else
                                                        {
                                                            @item.ModifiedDate;
                                                        }
                                                    }
                                                </td>
                                                <td>
                                                    @item.Status
                                                </td>
                                                <td>
                                                    @Ajax.ActionLink("Edit", "Edit", "ItemCompany", new { ItemCompanyID = item.ItemCompanyID }, new AjaxOptions { UpdateTargetId = "divCreate", HttpMethod = "get", OnSuccess = "onEditSuccess", LoadingElementId = "progress" }, new { @class = "btn btn-info btn-xs" }) |
                                                    @Ajax.ActionLink("Delete", "Delete", "ItemCompany", new { ItemCompanyID = item.ItemCompanyID }, new AjaxOptions { Confirm = "Are you sure you want to do this Item Company?", HttpMethod = "get", OnSuccess = "onDeleteSuccess", LoadingElementId = "progress" }, new { @class = "btn btn-danger btn-xs" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MWBTCustomerCreation/CCAPortal/Views/ItemCompany/Create.cshtml
@model WBT.DLCustomerCreation.ItemCompany
@using (Ajax.BeginForm("Save", "ItemCompany", null, new AjaxOptions
{
    UpdateTargetId = "divList",
    OnSuccess = "onCreateSuccess_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Brand Manufacturers Master</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Brand Manufacturer Name </label>
                                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Company Name", @autocomplete = "off", @required = "required" } })
                                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group" style="margin-top:40px;">
                                <label> @Html.CheckBoxFor(a => a.IsActive, new { @checked = "checked" })  Is Active</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $.validator.unobtrusive.parse(document);
</script>

MWBTCustomerCreation/CCAPortal/Views/ItemCompany/Edit.cshtml
@model WBT.DLCustomerCreation.ItemCompany
@using (Ajax.BeginForm("Update", "ItemCompany", null, new AjaxOptions
{
    UpdateTargetId = "divList",
    OnSuccess = "onEditSuccess_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Edit Brand Manufacturer</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Brand Manufacturer Name</label>
                                @Html.HiddenFor(model => model.ItemCompanyID)
                                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Company Name", @autocomplete = "off", @required = "required" } })
                                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group" style="margin-top:40px;">
                                <label> @Html.CheckBoxFor(a => a.IsActive)  Is Active</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $.validator.unobtrusive.parse(document);
</script>

MWBTCustomerCreation/CCAPortal/Views/ItemCompany/Index.cshtml
@{
    ViewBag.Title = "Brand Manufacturers";
}

<div class="main-panel" id="MainDiv">
    <div class="row">
        <div class="col-12 grid-margin">
            <div id="divCreate">
                @Html.Action("Create")
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 grid-margin">
            <div id="divList">
                @Html.Action("CompanyList")
            </div>
        </div>
    </div>
</div>

<div id="progress" class="modal">
    <div class="center" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            Loading, please wait... <img src="~/images/loading.gif" height="100" width="100" />
        </p>
    </div>
</div>

@section scripts {

    <script>
        function onCreateSuccess_Ajax(data) {
             Swal.fire({
                    text: data,
                }).then((result) => {
                    $("#divCreate").load('@Url.Action("Create", "ItemCompany")');
                    $("#divList").load('@Url.Action("CompanyList", "ItemCompany")');
                    setTimeout(function () {
                        loadDataTableWithButtons();
                    }, 1000);
                });
        }
        function onEditSuccess_Ajax(data) {
            Swal.fire({
                text: data.Message,
                }).then((result) => {
                    $("#divCreate").load('@Url.Action("Create", "ItemCompany")');
                    $("#divList").load('@Url.Action("CompanyList", "ItemCompany")');
                    setTimeout(function () {
                        loadDataTableWithButtons();
                    }, 1000);
                });
        }
        function onBegin_Ajax(data) {
        }
        function onErrorCreate(error) {

        }
        function Ajax_Edit_Failure(xhr, statusDescription) {
            swal(xhr.statusDescription);
        }
        function onEditSuccess() {
            $("#CompanyName").focus();
        }
        function onDeleteSuccess(data) {
            if (data.url) {
                window.location = '@Url.Action("Index", "Login")';
            }
            Swal.fire({
                text: data,
            }).then((result) => {
                $("#divList").load('@Url.Action("CompanyList", "ItemCompany")');
                setTimeout(function () {
                    $("#dataGrid").dataTable().fnDestroy();
                    loadDataTableWithButtons();
                }, 1000);
            });
        }
        function onEditCompleteCreate_Ajax() {

        }
        function Ajax_OnComplete() {

        }
        function onSaveCompleteCreate_Ajax() {

        }
    </script>
    <script>
        function btnCancel_Click() {
            $('#divCreate').load('@Url.Action("Create", "ItemCompany")');
            setTimeout(function () {
                LoadListBox();
            }, 1000);
        }
    </script>

    <script>
        jQuery(document).ready(function ($) {
            loadDataTableWithButtons();
        });
    </script>

}