MWBTCustomerCreation/CCAPortal/Controllers/BusinessSetMarginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WBT.Common;
using WBT.DLCustomerCreation;

namespace CCAPortal.Controllers
{
    public class BusinessSetMarginController : Controller
    {
        public CustomerCreations customerCreations = new CustomerCreations();
        public Margins pmargin = new Margins();
        public BusinessTypeProperties btmargin = new BusinessTypeProperties();
        public DLMargins dlMargins = new DLMargins();
        public static TimeZoneInfo INDIAN_ZONE = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");

        public int businesstypeid = 0;
        public string businessTypeName = "";
        // GET: BusinessSetMargin
        public ActionResult Index(string route, string routeName)
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                businesstypeid = Convert.ToInt32(route);
                businessTypeName = Helper.Decrypt(routeName, "sblw-3hn8-sqoy19");

                ViewBag.StateList = new SelectList(customerCreations.GetStateList(), "StateID", "StateName");
                ViewBag.DistrictList = new SelectList(customerCreations.GetDistricts(), "DistrictID", "DistrictName");
                ViewBag.CityList = new SelectList(customerCreations.GetAllCities(Session["UserID"].ToString()), "StateWithCityID", "VillageLocalityName");
                ViewBag.BranchList = new SelectList(customerCreations.GetBranchList(Session["OrgID"].ToString(), Session["UserID"].ToString(), Session["RoleName"].ToString()), "BranchID", "Name");

                businesstypeid = Convert.ToInt32(route);
                businessTypeName = Helper.Decrypt(routeName, "sblw-3hn8-sqoy19");
                btmargin.BusinessTypeName = businessTypeName;
                btmargin.BusinessTypeID = businesstypeid;
                return View(btmargin);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult LoadDetails(string route, string routeName)
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {


                ViewBag.StateList = new SelectList(customerCreations.GetStateList(), "StateID", "StateName");
                ViewBag.DistrictList = new SelectList(customerCreations.GetDistricts(), "DistrictID", "DistrictName");
                ViewBag.CityList = new SelectList(customerCreations.GetAllCities(Session["UserID"].ToString()), "StateWithCityID", "VillageLocalityName");
                ViewBag.BranchList = new SelectList(customerCreations.GetBranchList(Session["OrgID"].ToString(), Session["UserID"].ToString(), Session["RoleName"].ToString()), "BranchID", "Name");

                businesstypeid = Convert.ToInt32(route);
                businessTypeName = Helper.Decrypt(routeName, "sblw-3hn8-sqoy19");
                pmargin.BusinessTypeName = businessTypeName;

                return PartialView(pmargin);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

       [HttpPost]
        public JsonResult InsertData(BusinessTypeProperties marginsvalue)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                //businesstypeid = Convert.ToInt32(route);
                //businessTypeName = Helper.Decrypt(routeName, "sblw-3hn8-sqoy19");
                //btmargin.BusinessTypeName = businessTypeName;

                //marginsvalue.BusinessTypeID = businesstypeid;
                marginsvalue.OrgID = Session["OrgID"].ToString();
                marginsvalue.CreatedByID = Convert.ToInt32(Session["UserID"].ToString());
                BusinessTypeProperties Result = dlMargins.SaveBusinessMarginData(marginsvalue, marginsvalue.OrgID);
                return Json(Result); 
            }
        }

        
        public ActionResult PreviousBusinessTypeList(string route, string routeName)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            List<Margins> result = new List<Margins>();
            try
            {
                businesstypeid = Convert.ToInt32(route);
                result = dlMargins.GetBusinessTypeMarginDetails(Session["OrgID"].ToString(),businesstypeid);
            }
            catch (Exception ex)
            {
            }
            return PartialView(result);
        }

        //[HttpPost]
        //public ActionResult valu(Margins marginsvalues)
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return Json("error", JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        marginsvalues.OrgID = Session["OrgID"].ToString();
        //        marginsvalues.CreatedByID = Convert.ToInt32(Session["UserID"].ToString());
        //        Margins Result = dlMargins.SaveBusinessMarginData(marginsvalues, marginsvalues.OrgID);
        //        return Json(Result.DisplayMessage);
        //    }
        //}

    }
}

MWBTCustomerCreation/CCAPortal/Controllers/MarginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WBT.DLCustomerCreation;

namespace CCAPortal.Controllers
{
    public class MarginController : Controller
    {
        CustomerCreations customerCreations = new CustomerCreations();
        Margins margin = new Margins();
        DLMargins dlMargins = new DLMargins();

        // GET: Margin
        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["OrgID"] != null)
            {
                ViewBag.StateList = new SelectList(customerCreations.GetStateList(), "StateID", "StateName");
                ViewBag.DistrictList = new SelectList(customerCreations.GetDistricts(), "DistrictID", "DistrictName");
                ViewBag.CityList = new SelectList(customerCreations.GetAllCities(Session["UserID"].ToString()), "StateWithCityID", "VillageLocalityName");
                ViewBag.BranchList = new SelectList(customerCreations.GetBranchList(Session["OrgID"].ToString(), Session["UserID"].ToString(), Session["RoleName"].ToString()), "BranchID", "Name");

                return PartialView();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }


        public ActionResult BusinessList()
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            List<Margins> result = new List<Margins>();
            try
            {
                result = dlMargins.GetBusinessTypeData(Session["OrgID"].ToString());
            }
            catch (Exception ex)
            {
            }
            return PartialView(result);
        }

        [HttpPost]
        public ActionResult BusinessPopup(int BusinessTypeID)
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            //List<Margins> result = new List<Margins>();
            //try
            //{
            //   // result = dlMargins.GetBusinessTypeData(Session["OrgID"].ToString());
            //}
            //catch (Exception ex)
            //{
            //}
            ViewBag.StateList = new SelectList(customerCreations.GetStateList(), "StateID", "StateName");
            ViewBag.DistrictList = new SelectList(customerCreations.GetDistricts(), "DistrictID", "DistrictName");
            ViewBag.CityList = new SelectList(customerCreations.GetAllCities(Session["UserID"].ToString()), "StateWithCityID", "VillageLocalityName");
            ViewBag.BranchList = new SelectList(customerCreations.GetBranchList(Session["OrgID"].ToString(), Session["UserID"].ToString(), Session["RoleName"].ToString()), "BranchID", "Name");
            return PartialView();
        }

        public ActionResult CreditList()
        {
            if (Session["UserID"] == null || Session["OrgID"] == null)
            {
                return this.RedirectToAction("Index", "Login");
            }
            List<Margins> result = new List<Margins>();
            try
            {
                result = dlMargins.GetCreditTypeData(Session["OrgID"].ToString());
            }
            catch (Exception ex)
            {
            }
            return PartialView(result);
        }



        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Save(Brands brands)
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return this.RedirectToAction("Index", "Login");
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        Brands Result = dLBrands.SaveData(brands, Session["OrgID"].ToString(), Session["UserID"].ToString());
        //        return Json(Result.DisplayMessage);
        //    }
        //    else
        //    {
        //        IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
        //        return Json(new { allErrors });
        //    }
        //}

        //public ActionResult BrandList()
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return this.RedirectToAction("Index", "Login");
        //    }

        //    List<Brands> result = new List<Brands>();
        //    try
        //    {
        //        result = dLBrands.GetData(Session["OrgID"].ToString());
        //    }
        //    catch (Exception ex)
        //    {

        //    }
        //    return PartialView(result);
        //}

        //public ActionResult Edit(int BrandID)
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return Json(new { url = Url.Action("Index", "Login") });
        //    }
        //    if (BrandID == 0)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ViewBag.ItemCompanies = new SelectList(dLBrands.GetItemCompanies(Session["OrgID"].ToString()), "ItemCompanyID", "CompanyName");
        //    Brands brands = dLBrands.GetIBrandDetail(BrandID);

        //    if (brands == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return PartialView("Edit", brands);
        //}

        //public ActionResult Delete(int BrandID)
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return Json(new { url = Url.Action("Index", "Login") });
        //    }
        //    if (BrandID == 0)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Brands Result = dLBrands.DeleteBrand(BrandID, Session["OrgID"].ToString(), Session["UserID"].ToString());
        //    return Json(Result.DisplayMessage, JsonRequestBehavior.AllowGet);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Update(Brands brands)
        //{
        //    if (Session["UserID"] == null || Session["OrgID"] == null)
        //    {
        //        return Json(new { url = Url.Action("Index", "Login") });
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        Brands Result = dLBrands.SaveData(brands, Session["OrgID"].ToString(), Session["UserID"].ToString());
        //        return Json(new
        //        {
        //            Message = Result.DisplayMessage,
        //            AjaxReturn = PartialView("BrandList", dLBrands.GetData(Session["OrgID"].ToString()).ToList()).RenderToString()
        //        });
        //    }
        //    else
        //    {
        //        IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
        //        return Json(new
        //        {
        //            Message = allErrors,
        //            AjaxReturn = PartialView("BrandList", dLBrands.GetData(Session["OrgID"].ToString()).ToList()).RenderToString()
        //        });
        //    }
        //}
    }
}

MWBTCustomerCreation/CCAPortal/Views/BusinessSetMargin/Index.cshtml
@model WBT.DLCustomerCreation.BusinessTypeProperties

@{
    ViewBag.Title = "Business Type Margin";
}

@using (Ajax.BeginForm("InsertData", "BusinessSetMargin", null, new AjaxOptions
{
     OnSuccess = "onPromoSuccess_Ajax",
     ////OnFailure = "onFailure_Ajax",
     HttpMethod = "post",
     LoadingElementId = "progress"
}, new { @class = "form-sample" }))
{
    <div class="row">
       <div class="col-12">
          <div class="card card-primary">
             <div class="card-header">
               <h3 class="card-title">Business Type Margin</h3>
               <div class="card-tools">
                 <button type="button" class="btn btn-tool" data-card-widget="collapse">  <i class="fas fa-minus"></i> </button>
                 <button type="button" class="btn btn-tool" data-card-widget="remove"> <i class="fas fa-times"></i> </button>
               </div>
             </div>
          <div class="card-body">
              <div class="row">
                  <div class="col-md-3">
                     <div class="form-group">
                        <label> State </label>
                         <div class="input-group">
                            @Html.DropDownListFor(model => model.stateID, (SelectList)ViewBag.StateList, "Select", new { @class = "form-control dropdown listbox" })
                         </div>
                     </div>
                  </div>
                  <div class="col-md-3">
                     <div class="form-group">
                        <label> District </label>
                        <div class="input-group">
                           @Html.DropDownListFor(model => model.districtID, (SelectList)ViewBag.DistrictList, "Select", new { @class = "form-control dropdown listbox" })
                        </div>
                     </div>
                  </div>
                  <div class="col-md-3">
                     <div class="form-group">
                        <label> City </label>
                        <div class="input-group">
                            @Html.DropDownListFor(model => model.CityID, (SelectList)ViewBag.CityList, "Select", new { @class = "form-control dropdown listbox" })
                        </div>
                     </div>
                  </div>
                  <div class="col-md-3">
                      <div class="form-group">
                         <label>Branch</label>
                            <div class="input-group">
                               @Html.DropDownListFor(a => a.BranchID, (SelectList)ViewBag.BranchList, "Select", new { @class = "form-control listbox", })
                            </div>
                            @Html.ValidationMessageFor(model => model.BranchID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Business Type </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.BusinessTypeName, new { @readonly = "readonly", @class = "form-control" })
                                                @Html.HiddenFor(model => model.BusinessTypeID)
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label> Margin in % </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.Margin, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label> Margin After this Period </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.NextMargin, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label> From Effective Date </label>
                                            <div>

                                                @Html.TextBoxFor(model => model.FrmEffectiveDate, new { @class = "form-control dates" })

                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label> From Effective time </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.FrmEffectiveTime, new { @class = "form-control timepicker", @id="input_starttime" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>To Effective Date </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.ToEffectiveDate, new { @class = "form-control dates" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>To Effective Time </label>
                                            <div>
                                                @Html.TextBoxFor(model => model.ToEffectiveTime, new { @class = "form-control timepicker" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary" id="btnUpdate">Save</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            }

  






    <div class="row">
            <div class="col-12 grid-margin">
                <div id="divList">
                    @Html.Action("PreviousBusinessTypeList")
                </div>
            </div>
        </div>






<div id="progress" class="modal">
    <div class="center" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;">
        <p style="position: absolute; color: White; top: 50%; left: 45%;">
            Loading, please wait... <img src="~/images/loading.gif" height="100" width="100" />
        </p>
    </div>
</div>

@section scripts {

    <script>
        function onPromoSuccess_Ajax() {
            Swal.fire({
                title: 'Success!!',
                text: 'Successfully',
                icon: 'success',
            }).then((result) => {
                window.location = '@Url.Action("Index", "Margin")';
            });
        }

        function onSuccess_Ajax() {
        }
        function onCompleteCreate_Ajax() {
        }
        function onCreateSuccess_Ajax() {
        }
        function onEditSuccess_Ajax() {
        }
        function onEditSuccess() {

        }
        function onBegin_Ajax(data) {
        }
        function onEditCompleteCreate_Ajax() {
        }
        function onFailure_Ajax() {
            Swal.fire({
                title: 'Error',
                text: "Please try again later",
                icon: 'error',
            }).then((result) => { });
        }
        function Ajax_Edit_Failure() {
        }
        function Ajax_OnComplete() {
        }
        function onSaveCompleteCreate_Ajax() {
        }

        $(document).ready(function () {

            // Time Picker Initialization
$('#input_starttime').pickatime({});
        });
        $(".dates").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
    </script>
}

MWBTCustomerCreation/CCAPortal/Views/BusinessSetMargin/LoadDetails.cshtml
@model WBT.DLCustomerCreation.Margins
                                        
@using (Ajax.BeginForm("InsertData", "BusinessSetMargin", null, new AjaxOptions
{
    OnSuccess = "onPromoSuccess_Ajax",
    ////OnFailure = "onFailure_Ajax",
    HttpMethod = "post",
    LoadingElementId = "progress"
}, new { @class = "form-sample", @id = "frm-promote", @enctype = "multipart/form-data" }))
{


    <div class="row" id="divList">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Business Set Margin</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">  <i class="fas fa-minus"></i> </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"> <i class="fas fa-times"></i> </button>
                    </div>
                </div>

                <div class="card-body">

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> State </label>
                                <div class="input-group">
                                    @Html.DropDownListFor(a => a.StateList, (SelectList)ViewBag.StateList, new { @class = "form-control dropdown listbox", @multiple = "multiple" })
                                    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> District </label>
                                <div class="input-group">
                                    @Html.DropDownListFor(a => a.DistrictList, (SelectList)ViewBag.DistrictList, new { @class = "form-control dropdown listbox", @multiple = "multiple" })
                                    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> City </label>
                                <div class="input-group">
                                    @Html.DropDownListFor(a => a.CityList, (SelectList)ViewBag.CityList, new { @class = "form-control dropdown listbox" })
                                    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Branch</label>
                                <div class="input-group">
                                    @Html.DropDownListFor(model => model.BranchList, (SelectList)ViewBag.BranchList, new { @class = "form-control listbox", @multiple = "multiple" })
                                    
                                </div>
                                @Html.ValidationMessageFor(model => model.BranchList, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Business Type </label>
                                <div>
                                    @Html.TextBoxFor(m => m.BusinessTypeName, new { @readonly="readonly", @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> Margin in % </label>
                                <div>
                                    @Html.TextBoxFor(m => m.SetMargin, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> Margin After this Period </label>
                                <div>
                                    @Html.TextBoxFor(m => m.NextMargin, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> From Effective Date </label>
                                <div>
                                    @*class="input-group date" id="reservationdate" data-target-input="nearest"*@
                                    @Html.TextBoxFor(m => m.FrmEffectiveDate, new { @class = "form-control dated" })
                                    @*<div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>*@
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label> From Effective time </label>
                                @*<div class="input-group date" id="timepicker" data-target-input="nearest">
                        @Html.TextBoxFor(m => m.FrmEffectiveTime, new { @class = "form-control datetimepicker-input", @data_target="#timepicker" })
                        <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                        </div>
                    </div>*@
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>To Effective Date </label>
                                <div>
                                    @*class="input-group date" id="todates" data-target-input="nearest"*@
                                    @Html.TextBoxFor(m => m.ToEffectiveDate, new { @class = "form-control dated" })
                                    @*<div class="input-group-append" data-target="#todates" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>*@
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>To Effective Time </label>
                                @*<div class="input-group date" id="timepicker1" data-target-input="nearest">
                        @Html.TextBoxFor(m => m.ToEffectiveTime, new { @class = "form-control datetimepicker-input", @data_target = "#timepicker1" })
                        <div class="input-group-append" data-target="#timepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                        </div>
                    </div>*@
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary" id="btnUpdate">Save</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
}